# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ctmcForwardBackward <- function(ts, theta, obs) {
    .Call('_chenliuuHW4_ctmcForwardBackward', PACKAGE = 'chenliuuHW4', ts, theta, obs)
}

ctmcViterbi <- function(ts, theta, obs) {
    .Call('_chenliuuHW4_ctmcViterbi', PACKAGE = 'chenliuuHW4', ts, theta, obs)
}

